services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    repo: https://github.com/Vlad000555/n8n
    dockerfilePath: Dockerfile
    envVars:
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-1-vgdz.onrender.com
      - key: VUE_APP_URL
        value: https://n8n-1-vgdz.onrender.com
      - key: N8N_HOST
        value: n8n-1-vgdz.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 443
